# Generated by Django 5.0 on 2024-01-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('RUS', 'Россия'), ('ARM', 'Армения'), ('BLR', 'Беларусь'), ('DEU', 'Германия'), ('GEO', 'Грузия'), ('CHN', 'Китай')], default='RUS', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Номер телефона'),
        ),
    ]
