# Generated by Django 5.0 on 2024-01-15 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_alter_user_avatar_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field_uuid',
            field=models.UUIDField(default=uuid.UUID('1fc03a88-d92d-4240-91ba-3bae3990b63d'), unique=True, verbose_name='UUID'),
        ),
    ]
