# Generated by Django 5.0 on 2024-01-16 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_field_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field_uuid',
            field=models.UUIDField(default=uuid.UUID('c06ea54e-def0-4217-ab77-2c8fa2b81df5'), unique=True, verbose_name='UUID'),
        ),
    ]
