# Generated by Django 5.0 on 2024-01-17 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_field_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field_uuid',
            field=models.UUIDField(default=uuid.UUID('8e067701-7336-4e98-bce6-a10dc29d6b97'), unique=True, verbose_name='UUID'),
        ),
    ]
