# Generated by Django 5.0 on 2024-01-18 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_field_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field_uuid',
            field=models.UUIDField(default=uuid.UUID('1a311322-9417-45b0-b881-71ec2ed5c2f7'), unique=True, verbose_name='UUID'),
        ),
    ]
