# Generated by Django 5.0 on 2024-01-18 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_field_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field_uuid',
            field=models.UUIDField(default=uuid.UUID('dc46c09f-9ee4-49b4-9695-54a982baf48b'), unique=True, verbose_name='UUID'),
        ),
    ]
