# Generated by Django 5.0 on 2024-01-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Может публиковать продукт')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
